# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "qr-code-sample-app"
client_id = "ec815a2802e2adc96c7b0f0a26cd5de7"
application_url = "https://lets-metric-designing-invention.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_discounts"

[auth]
redirect_urls = [
  "https://lets-metric-designing-invention.trycloudflare.com/auth/callback",
  "https://lets-metric-designing-invention.trycloudflare.com/auth/shopify/callback",
  "https://lets-metric-designing-invention.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "infowind-shop.myshopify.com"
